# theme: jekyll-theme-minimal
# Site settings
markdown: kramdown
# {% raw %}{% seo %}{% endraw %}
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap



url: "https://christopherjohndillon.github.io" # the base hostname & protocol for your site
